name: glih
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi>=0.115.0
      - uvicorn[standard]>=0.23.0
      - streamlit>=1.38.0
      - pandas>=2.2.0
      - requests>=2.32.0
      - python-dotenv>=1.0.1
